{% set name = "open-radar-data" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/open-radar-data-{{ version }}.tar.gz
  sha256: 66f40f95333c7f4a3f5af53dc7869a2bae7a9d1f3dee4380cb4ccc4b06a47b8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - wheel
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.9
    - pooch

test:
  imports:
    - open_radar_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openradar/open-radar-data
  summary: Provides utility functions for accessing data repository for Project Pythia examples/notebooks
  dev_url: https://github.com/openradar/open-radar-data
  license: MIT
  license_file: LICENSE
  description: A place to share radar data with the community, shared between the open radar package

extra:
  recipe-maintainers:
    - HeavyTony2
    - mgrover1
    - kmuehlbauer
