{% set name = "open-radar-data" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2d7c935f0c60adb0309cade8237437db4a5dc766c5c04e36f7b67e05485fbf0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=7.0
    - pip
  run:
    - python >={{ python_min }}
    - pooch

test:
  imports:
    - open_radar_data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/openradar/open-radar-data
  summary: Provides utility functions for accessing data repository for Project Pythia examples/notebooks
  dev_url: https://github.com/openradar/open-radar-data
  license: MIT
  license_file: LICENSE
  description: A place to share radar data with the community, shared between the open radar package

extra:
  recipe-maintainers:
    - HeavyTony2
    - mgrover1
    - kmuehlbauer
